---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: trove_upstart_common_init.yml
  vars:
    program_name: "{{ trove_service_conductor_program_name }}"
    program_config_options: "{{ trove_service_conductor_program_config_options }}"
    service_name: "{{ trove_service_name }}"
    system_user: "{{ trove_system_user_name }}"
    system_group: "{{ trove_system_group_name }}"
    service_home: "{{ trove_system_home_folder }}"
  when: >
    inventory_hostname in groups['trove_conductor'] and
    trove_service_program_enabled == true
  tags:
    - upstart-init

- include: trove_upstart_common_init.yml
  vars:
    program_name: "{{ trove_service_task_manager_program_name }}"
    program_config_options: "{{ trove_service_task_manager_program_config_options }}"
    service_name: "{{ trove_service_name }}"
    system_user: "{{ trove_system_user_name }}"
    system_group: "{{ trove_system_group_name }}"
    service_home: "{{ trove_system_home_folder }}"
  when: >
    inventory_hostname in groups['trove_taskmanager'] and
    trove_service_program_enabled == true
  tags:
    - upstart-init

- include: trove_upstart_common_init.yml
  vars:
    program_name: "{{ trove_service_api_program_name }}"
    program_config_options: "{{ trove_service_api_program_config_options }}"
    service_name: "{{ trove_service_name }}"
    system_user: "{{ trove_system_user_name }}"
    system_group: "{{ trove_system_group_name }}"
    service_home: "{{ trove_system_home_folder }}"
  when: >
    inventory_hostname in groups['trove_api'] and
    trove_service_program_enabled == true
  tags:
    - upstart-init
